#!/usr/bin/env bash
source "$(dirname "$0")/portable.sh"
# mkiso.sh — assemble build/causticos.iso: kernel + bootloader + the live root.
#
# The ISO is self-contained. It carries the root volume as a Limine module (a
# CSVI sparse container), so booting it needs no disk at all — which is the
# whole point of the reform this belongs to. Passing --no-live leaves the module
# out, which is how the disk-boot path stays regression-tested.
#
# Invoked from the Causticfile:  caustic-mk run iso -- [--profile P] [--no-live]
set -euo pipefail

cd "$(dirname "$0")/.."

PROFILE="${COS_PROFILE:-desktop}"
LIVE=1
LIMINE_DIR="${LIMINE_DIR:-/usr/share/limine}"
OUT="build/causticos.iso"
CMDLINE=""
ROOT_ARGS=()

while [ $# -gt 0 ]; do
    case "$1" in
        --profile) PROFILE="$2"; shift 2 ;;
        --profile=*) PROFILE="${1#*=}"; shift ;;
        --no-live) LIVE=0; shift ;;
        --out) OUT="$2"; shift 2 ;;
        --cmdline) CMDLINE="$2"; shift 2 ;;
        # Passed straight to mkroot: "this profile, but /init is that, and these
        # files are on it". A test harness wants a whole system with itself as
        # init, which is one ISO rather than a disk to attach — and since the
        # live root outranks a disk, attaching one would not even be read.
        --init) ROOT_ARGS+=(--init "$2"); shift 2 ;;
        --add) ROOT_ARGS+=(--add "$2"); shift 2 ;;
        --size) ROOT_ARGS+=(--size "$2"); shift 2 ;;
        *) echo "mkiso: unknown option '$1'" >&2; exit 1 ;;
    esac
done

[ -f build/kernel.elf ] || { echo "mkiso: build/kernel.elf missing — run 'caustic-mk build kernel'" >&2; exit 1; }

for f in limine-bios.sys limine-bios-cd.bin limine-uefi-cd.bin BOOTX64.EFI; do
    [ -f "$LIMINE_DIR/$f" ] || { echo "mkiso: $LIMINE_DIR/$f missing — install limine, or set LIMINE_DIR" >&2; exit 1; }
done

rm -rf build/iso
mkdir -p build/iso/boot/limine build/iso/EFI/BOOT "$(dirname "$OUT")"
cp build/kernel.elf build/iso/boot/
cp "$LIMINE_DIR/limine-bios.sys"     build/iso/boot/limine/
cp "$LIMINE_DIR/limine-bios-cd.bin"  build/iso/boot/limine/
cp "$LIMINE_DIR/limine-uefi-cd.bin"  build/iso/boot/limine/
cp "$LIMINE_DIR/BOOTX64.EFI"         build/iso/EFI/BOOT/

# The live root. Built fresh here rather than reused: the ISO and the root it
# carries have to describe the same system, and a stale container is the kind of
# mismatch that costs an hour to notice.
MODULE_LINE=""
if [ "$LIVE" = 1 ]; then
    "$PY" scripts/mkroot.py --profile "$PROFILE" \
        ${ROOT_ARGS[@]+"${ROOT_ARGS[@]}"} --csvi build/iso/boot/rootfs.csvi -q
    ROOT_CSVI="build/iso/boot/rootfs.csvi"
    MODULE_LINE="    module_path: boot():/boot/rootfs.csvi"
fi

# limine.conf is generated, because whether the module line is present is a
# build-time choice (--no-live) and a checked-in file cannot express both.
{
    echo "# Generated by scripts/mkiso.sh — edit that, not this."
    echo "timeout: 0"
    echo "quiet: yes"
    echo ""
    echo "/causticos"
    echo "    protocol: limine"
    echo "    kernel_path: boot():/boot/kernel.elf"
    if [ -n "$CMDLINE" ]; then
        # The kernel command line comes from HERE, not from QEMU's -append:
        # -append only reaches a kernel loaded with -kernel, and this one is
        # loaded by Limine off the ISO. Passing -append with a bootloader in the
        # picture silently does nothing, which is a bad way to find out.
        echo "    cmdline: $CMDLINE"
    fi
    if [ "$LIVE" = 1 ]; then
        echo "    # The live root: a CSVI sparse container the kernel expands into a"
        echo "    # RAM-backed FAT32 volume and mounts as \"/\". This is why the ISO"
        echo "    # boots the whole system with no disk attached."
        echo "$MODULE_LINE"
    fi
    # The resolution is a preference — fb.cst reads width/height/pitch/bpp back
    # from whatever Limine actually got.
    echo "    resolution: 1280x720x32"
} > build/iso/boot/limine/limine.conf

xorriso -as mkisofs \
    -b boot/limine/limine-bios-cd.bin -no-emul-boot \
    -boot-load-size 4 -boot-info-table \
    --efi-boot boot/limine/limine-uefi-cd.bin \
    -efi-boot-part --efi-boot-image --protective-msdos-label \
    build/iso -o "$OUT" 2>/dev/null

limine bios-install "$OUT" 2>/dev/null

ISO_BYTES=$(stat -c%s "$OUT")
if [ "$LIVE" = 1 ]; then
    ROOT_BYTES=$(stat -c%s build/iso/boot/rootfs.csvi)
    LC_ALL=C printf 'iso: %s  %s bytes (%.1f MiB) — live, profile %s (root %s bytes)%s\n' \
        "$OUT" "$ISO_BYTES" "$(echo "$ISO_BYTES/1048576" | bc -l)" "$PROFILE" "$ROOT_BYTES" "${CMDLINE:+, cmdline \"$CMDLINE\"}"
else
    LC_ALL=C printf 'iso: %s  %s bytes (%.1f MiB) — NO live root (--no-live): needs a disk to boot%s\n' \
        "$OUT" "$ISO_BYTES" "$(echo "$ISO_BYTES/1048576" | bc -l)" "${CMDLINE:+, cmdline \"$CMDLINE\"}"
fi
